### ISSUE TITLE
why we always failed  in installing  hyvr 

### ISSUE THREAD

**Issue by cdzhou2015** [driftingtides/hyvr#1] opened 2019-04-01 12:57 UTC
When I type >pip install hyvr, the following error information :
Collecting hyvr
  Using cached https://files.pythonhosted.org/packages/1b/6a/5064c7fc432607d8f4f858d334faf7e4f14cd7e55d29cce3035232824a28/hyvr-1.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\cdzhou\AppData\Local\Temp\pip-install-8wlnhj1r\hyvr\setup.py", line 58, in <module>
        ext_modules = cythonize(extensions)
      File "e:\anaconda3\lib\site-packages\Cython\Build\Dependencies.py", line 897, in cythonize
        aliases=aliases)
      File "e:\anaconda3\lib\site-packages\Cython\Build\Dependencies.py", line 777, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "e:\anaconda3\lib\site-packages\Cython\Build\Dependencies.py", line 102, in nonempty
        raise ValueError(error_msg)
    ValueError: 'hyvr/classes/grid.pyx' doesn't match any files
Command "python setup.py egg_info" failed with error code 1 in C:\users\cdzhou\appdata\local\temp\pip-install-8wlnhjlr\hyvr\

please reply to my email cdzhou@qq.com.Thanks a lot!

**Comment by p-ortega** [comment] 2019-10-03 08:14
Hi, I'm getting the same issue, did you manage to get a workaround?

Cheers.

**Comment by p-ortega** [comment] 2019-10-03 09:57
I got a solution, I had and issue with the C++ compiler in windows, I followed the instructions from here https://stackoverflow.com/questions/41724445/python-pip-on-windows-command-cl-exe-failed/41724634 and it worked smoothly. Also, I installed the exact dependencies on the environment, but I don't know if has some influence in the overall installation.

**Comment by s-scherrer** [comment] 2019-10-18 06:08
Hi,
I'm very sorry that I'm answering so late, it seems I didn't have notifications for this project enabled and I wasn't working on hyvr the last year.

Unfortunately I cannot reproduce the issue, since I do not have a Windows system available. I assume it might have been an issue with path names in setup.py, that should be fixed by my latest commit. At the moment this is only available in the github-version and not on PyPI, so you have to clone the repository and install from source, which should work like this on a linux system:
```
$ git clone git@github.com:driftingtides/hyvr.git
$ cd hyvr
$ pip install .
```

I'm working on publishing this on PyPI as well.

**Comment by s-scherrer** [comment] 2019-10-20 17:36
I uploaded a new version (1.0.1) as sdist to PyPI which should fix the original issue. However, it still requires a C++ compiler, which is probably inconvenient for most Windows users, so I will try to upload a wheel for Windows in a few days.

The issue will be closed once a working installation on a Windows system is confirmed.

**Comment by s-scherrer** [comment] 2019-10-26 20:08
Uploaded a windows wheel as version 1.0.3, installation on windows should work now. It might however be necessary to install numpy separately before installing HyVR.

**Closed as completed by s-scherrer** 2019-10-26 20:08 UTC
